/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const Registration = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllRegistrationsSorted' : IDL.Func(
      [],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'initializeActorAdmin' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const Registration = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : UserRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllRegistrationsSorted' : IDL.Func(
        [],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'initializeActorAdmin' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };